from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]

def page(title, description, body, prefix='./', tool=None, home=False):
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{escape(description, quote=True)}">
  <meta name="theme-color" content="#f6f7f2">
  <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' https://cdn.jsdelivr.net 'wasm-unsafe-eval'; style-src 'self'; img-src 'self' blob: data:; connect-src 'self' https://cdn.jsdelivr.net; worker-src 'self'; object-src 'none'; base-uri 'self'; form-action 'none'">
  <title>{escape(title)} · Privacy Toolbox</title>
  <link rel="icon" href="{prefix}assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="{prefix}assets/css/main.css">
  <script type="module" src="{prefix}assets/js/app.js"></script>
</head>
<body{f' data-tool="{tool}"' if tool else ''}{' class="home-page"' if home else ''}>
  <a class="skip" href="#main">Skip to content</a>
  <header class="site-header"><a class="brand" href="{prefix}"><span class="brand-icon" aria-hidden="true">▦</span> Privacy Toolbox<span class="version"> / 20 tools</span></a><nav aria-label="Main navigation"><a href="{prefix}#tools">All tools</a><a href="{prefix}about/">About &amp; privacy <span aria-hidden="true">↗</span></a></nav></header>
  <main id="main">{body}</main>
  <footer><a class="brand small" href="{prefix}"><span class="brand-icon" aria-hidden="true">▦</span> Privacy Toolbox</a><span>{'20 tools for everyday tasks' if home else 'A small toolkit. A little more privacy.'}</span><a href="{prefix}about/">How it works ↗</a></footer>
</body>
</html>
'''


def select(key, label, choices):
    return f'<label for="{key}">{label}</label><select id="{key}" name="{key}">' + ''.join(f'<option value="{v}">{t}</option>' for v,t in choices) + '</select>'


def check(key, label, checked=False):
    return f'<label class="checkbox"><input type="checkbox" id="{key}" name="{key}" {"checked" if checked else ""}> {label}</label>'


def number(key, label, value, minimum, maximum):
    return f'<label for="{key}">{label}</label><input class="number" id="{key}" name="{key}" type="number" value="{value}" min="{minimum}" max="{maximum}" step="1" required>'


def text(label='Input', placeholder='Type or paste here…', key='text'):
    return f'<div id="{key}-field"><label for="{key}">{label}</label><textarea id="{key}" name="{key}" rows="8" spellcheck="false" placeholder="{escape(placeholder, quote=True)}"></textarea></div>'


def drop(image=False, hashed=False):
    return f'''<div class="dropzone" id="dropzone"><span class="drop-icon" aria-hidden="true">↑</span><strong>Drop {'an image' if image else 'a file'} here</strong><span>or choose one from your device</span><input id="file" type="file" aria-label="Choose a file" {'accept="image/jpeg,image/png,image/webp,image/bmp,.bmp"' if image else ''}><small>{'Read in 4 MiB chunks' if hashed else '64 MiB maximum'}{' · Still images · 20 megapixels' if image else ''}</small></div><p id="file-info" class="file-info" aria-live="polite">No file selected</p>'''


def quality():
    return '<div id="quality-field"><label for="quality">Quality <output id="quality-value" for="quality">75</output></label><input id="quality" name="quality" type="range" min="30" max="100" value="75"></div>'


FORMATS = [('original','Keep original'),('JPEG','JPEG'),('PNG','PNG'),('WEBP','WebP'),('BMP','BMP')]
IMAGE_NOTE = 'Still images only. EXIF orientation is applied and embedded metadata is removed. JPEG is lossy. JPEG/BMP use a white background for transparency. Removing color profiles can change colors.'
TOOLS = [
 dict(slug='file-hash', action='hash', icon='#', title='File Hash Calculator', category='Files', desc='Calculate SHA-256, SHA-512, and other checksums without uploading your file.',
      fields=drop(hashed=True)+select('algorithm','Hash algorithm',[(x,y) for x,y in [('sha256','SHA-256'),('sha384','SHA-384'),('sha512','SHA-512'),('sha1','SHA-1 (legacy)'),('md5','MD5 (legacy)')]]),
      button='Calculate hash', note='SHA-1 and MD5: Legacy algorithm — not recommended for security purposes.', how='Python hashlib updates one digest from 4 MiB chunks. The next chunk is read only after the previous one is processed.', faq=('Can I hash a large file?','Yes. Hashing reads bounded chunks and reports progress instead of loading the entire file into memory. You can cancel at any time.')),
 dict(slug='remove-image-metadata', action='image-metadata', icon='▧', title='Image Metadata Remover', category='Files', desc='Inspect and remove EXIF, GPS, and embedded image metadata.', fields=drop(True),button='Remove metadata',note=IMAGE_NOTE,
      how='Pillow first reads metadata for your inspection. Removal creates a new image from oriented pixels, without the original metadata containers.', faq=('Does this hide what is visible in the photo?','No. Faces, documents, and landmarks in the picture remain visible. GPS coordinates are displayed locally without maps or network lookups.')),
 dict(slug='image-compressor',action='image-compressor',icon='↘',title='Image Compressor',category='Files',desc='Compress JPEG, PNG, and WebP images on your device.',fields=drop(True)+select('output','Output format',FORMATS[:4])+quality(),button='Compress image',note=IMAGE_NOTE,
      how='Pillow re-encodes the image with your selected format and quality. PNG uses lossless optimization. The result shows actual bytes saved.',faq=('Will every image become smaller?','No. Already optimized images may grow. The exact output size is shown after processing; no unmeasured size estimate is displayed.')),
 dict(slug='image-resizer',action='image-resizer',icon='↔',title='Image Resizer',category='Files',desc='Change image dimensions with aspect ratio controls and quick presets.',fields=drop(True)+number('width','Width (px)',1920,1,20000000)+number('height','Height (px)',1080,1,20000000)+check('keep_aspect','Keep aspect ratio',True)+'<div class="presets">'+''.join(f'<button type="button" class="secondary" data-preset="{v}">{label}</button>' for v,label in [('25','25%'),('50','50%'),('75','75%'),('1920px','1920px'),('1080px','1080px')])+'</div>'+select('output','Output format',FORMATS)+quality(),button='Resize image',note=IMAGE_NOTE,
      how='Pillow resizes oriented pixels with Lanczos resampling. Percentage presets use original dimensions; pixel presets limit the longest side without upscaling.',faq=('What is the size limit?','Input and output are limited to 20 megapixels. With Keep aspect ratio enabled, the last edited dimension determines the other dimension.')),
 dict(slug='image-converter',action='image-converter',icon='⇄',title='Image Converter',category='Files',desc='Convert between PNG, JPEG, WebP, and BMP.',fields=drop(True)+select('output','Convert to',FORMATS[1:])+quality(),button='Convert image',note=IMAGE_NOTE,
      how='Pillow decodes the source pixels and encodes a fresh file in the selected format. Quality applies to JPEG and WebP.',faq=('Are HEIC, AVIF, or animations supported?','No. This version accepts still JPEG, PNG, WebP, and BMP images. BMP output can be much larger.')),
 dict(slug='url-cleaner',action='url-cleaner',icon='↗',title='Tracking URL Cleaner',category='Privacy',desc='Remove known tracking parameters and keep the link you need.',fields=text('URL to clean','https://example.com/?utm_source=newsletter&id=42')+check('remove_ref','Also remove ref and referrer (may affect the destination)'),button='Clean URL',note='Only known trackers are removed by default. Links are never opened automatically.',how='Python urllib.parse splits the URL; known tracking keys are removed while retained query segments keep their original encoding and order.',faq=('Does this make a link anonymous?','No. The destination can still track visits. The optional ref/referrer setting may remove functional parameters.')),
 dict(slug='password-generator',action='password-generator',icon='✳',title='Password Generator',category='Privacy',desc='Generate a random password with your choice of length and characters.',fields=number('length','Length',20,4,256)+''.join(check(k,t,True) for k,t in [('uppercase','Uppercase'),('lowercase','Lowercase'),('numbers','Numbers'),('symbols','Symbols')])+check('avoid_similar','Avoid similar characters (I, l, 1, O, 0, o)'),button='Generate password',note='Passwords are never saved in history or browser storage. Copy only when you are ready to use one.',how='Python secrets uses cryptographic randomness. Candidates are generated from the selected alphabet until every selected group is represented.',faq=('Is strength guaranteed?','No. Length and randomness help, but safe storage and avoiding reuse matter too. The entropy estimate counts valid outputs under the selected character rules; it assumes a sound random source. It is not a promise about password storage or reuse. There is no weak random fallback.')),
 dict(slug='uuid-generator',action='uuid-generator',icon='⠿',title='UUID Generator',category='Privacy',desc='Generate UUID v4 identifiers individually or in batches.',fields=number('amount','Amount (UUID v4)',5,1,1000),button='Generate UUIDs',note='UUID v4 uses random bits. Collisions are extremely unlikely, but not mathematically impossible.',how='Python uuid.uuid4 creates identifiers with UUID v4 version and variant bits. Copy individual rows or download the batch as TXT.',faq=('Can I use these as ordered IDs?','UUID v4 values are random, not chronological. This tool does not generate time-ordered UUID versions.')),
 dict(slug='random-token',action='random-token',icon='∗',title='Random Token Generator',category='Privacy',desc='Create cryptographically random hex, URL-safe, or Base64 tokens.',fields=select('mode','Token type',[('urlsafe','URL-safe'),('hex','Hex'),('base64','Base64')])+number('bytes','Random bytes',32,1,1024),button='Generate token',note='Entropy is based on random bytes, not encoded character count. Tokens are not stored.',how='Python secrets generates random bytes. Hex, URL-safe Base64, or standard Base64 encodes those same random bits.',faq=('What does 32 bytes mean?','32 random bytes provide 256 bits of source entropy. Encoding changes the number of displayed characters, not the source entropy.')),
 dict(slug='json-formatter',action='json',icon='{ }',title='JSON Formatter',category='Data',desc='Format, minify, and sort JSON with useful error locations.',fields=select('mode','Operation',[('format','Format'),('minify','Minify'),('sort','Sort keys'),('validate','Validate')])+select('indent','Indent',[('2','2 spaces'),('4','4 spaces')])+check('sort_keys','Sort keys')+text('JSON','{"name":"John","active":true}'),button='Process JSON',note='Duplicate keys and non-JSON constants are rejected. Decimal values use Python floating-point precision.',how='The shared strict Python JSON parser checks syntax before formatting or minifying. Whole-number precision is retained within Python limits.',faq=('Why reject duplicate keys?','Keeping only the final value would silently lose data. Resolve the duplicate before formatting.')),
 dict(slug='json-validator',action='json-validator',icon='✓',title='JSON Validator',category='Data',desc='Validate JSON syntax and locate errors by line and column.',fields=text('JSON','{"valid":true}'),button='Validate JSON',note='Checks syntax and duplicate keys, not JSON Schema.',how='Uses the same strict parser as JSON Formatter. Objects, arrays, strings, numbers, booleans, and null can all be valid top-level JSON.',faq=('Does valid JSON mean my data is correct?','No. Syntax validation does not check business rules, required fields, or a schema.')),
 dict(slug='base64',action='base64',icon='64',title='Base64 Encoder / Decoder',category='Data',desc='Encode and decode UTF-8 text or binary files with Base64.',fields=select('mode','Conversion',[('encode-text','Text → Base64'),('decode-text','Base64 → text'),('encode-file','File → Base64'),('decode-file','Base64 → file')])+text()+'<div id="file-field" hidden>'+drop()+'</div>',button='Convert',note='Base64 is encoding, not encryption. Decoded files use .bin because the encoding does not contain the original filename.',how='Python base64 performs strict decoding with whitespace allowed. Text is UTF-8; file modes preserve arbitrary bytes.',faq=('Why does text decoding fail for some inputs?','The decoded bytes may be a binary file rather than UTF-8. Choose Base64 → file to download them.')),
 dict(slug='csv-json',action='csv-json',icon='▤',title='CSV ↔ JSON Converter',category='Data',desc='Convert CSV tables to JSON arrays and JSON records to CSV.',fields=select('mode','Direction',[('csv-json','CSV → JSON'),('json-csv','JSON → CSV')])+check('safe_export','Protect spreadsheet export from formula interpretation',True)+text('CSV or JSON','name,age\nJohn,31\nAnna,28'),button='Convert',note='CSV → JSON keeps values as strings. JSON → CSV requires flat objects. Missing/null values become empty fields.',how='Python csv handles quoted commas, quotes, and multiline fields. Headers must be unique and non-empty. JSON columns follow first-seen key order.',faq=('Does safe export change my values?','Yes. It prefixes formula-like cells and headers with an apostrophe. Disable it only when you need exact values and understand how your spreadsheet treats them.')),
 dict(slug='text-cleaner',action='text-cleaner',icon='Aa',title='Text Cleaner',category='Text',desc='Tidy whitespace, blank lines, tabs, and non-printable characters.',fields=text()+''.join(check(k,t,v) for k,t,v in [('extra_spaces','Remove extra spaces',True),('empty_lines','Remove empty lines',True),('trim','Trim lines',True),('tabs','Convert tabs to 4 spaces',False),('normalize_endings','Normalize line endings to LF',False),('non_printable','Remove non-printable characters',False)]),button='Clean text',note='Character counts use Unicode code points. Line endings are preserved unless normalization is selected.',how='Python applies only your selected cleanup operations, preserving line boundaries. Removing non-printable characters keeps tabs and line endings.',faq=('Will this change meaningful whitespace?','It can. Check the options before processing code, poetry, or other text where indentation matters.')),
 dict(slug='remove-duplicate-lines',action='remove-duplicate-lines',icon='≠',title='Duplicate Line Remover',category='Text',desc='Remove repeated lines and see exactly how many were removed.',fields=text()+check('keep_order','Keep original order',True)+check('ignore_case','Ignore case')+check('trim','Trim spaces'),button='Remove duplicates',note='The first occurrence is retained. Without Keep original order, lines are sorted by their comparison key.',how='Python compares complete lines, with optional Unicode case folding and trimming. A trailing newline does not create a phantom line.',faq=('What happens to blank lines?','Blank lines are values too: one is retained. A completely empty input contains zero lines.')),
 dict(slug='text-diff',action='text-diff',icon='±',title='Text Diff',category='Text',desc='Compare two texts and inspect added, removed, and changed lines.',fields=text('Original text')+text('Modified text',key='modified'),button='Compare texts',note='Maximum 200,000 characters and 5,000 lines per input. Changed pairs are included in added/removed totals.',how='Python difflib produces a unified line diff. Missing final newlines are marked explicitly. User content is displayed as text, never interpreted as HTML.',faq=('Can I cancel a long comparison?','Yes. Cancel terminates the Worker and the next operation starts a fresh engine.')),
 dict(slug='timestamp',action='timestamp',icon='◷',title='Timestamp Converter',category='Developer',desc='Convert Unix seconds or milliseconds to dates and back.',fields=select('mode','Direction',[('unix','Unix timestamp → date'),('date','ISO date → Unix timestamp')])+select('unit','Timestamp unit',[('seconds','Seconds'),('milliseconds','Milliseconds')])+text('Timestamp or ISO 8601 date','1729829382'),button='Convert timestamp',note='Dates without a timezone are treated as UTC. Choose seconds or milliseconds explicitly.',how='Python converts against the UTC epoch with microsecond precision. The browser also displays the instant in its local timezone.',faq=('Are negative timestamps supported?','Yes, within years 1–9999. Fractional values are supported up to microsecond precision; the browser local display has millisecond precision.')),
 dict(slug='url-encoder',action='url-encoder',icon='%20',title='URL Encoder / Decoder',category='Developer',desc='Percent-encode a query value or decode UTF-8 URL text.',fields=select('mode','Operation',[('encode','Encode'),('decode','Decode')])+select('scope','Encoding scope',[('parameter','Query parameter'),('full','Full URL (keep delimiters)')])+text(),button='Convert URL text',note='Spaces encode as %20. A literal + is not treated as a space. Full URL mode preserves URL delimiters.',how='Python urllib.parse quotes or unquotes UTF-8 bytes. Invalid percent escapes and invalid decoded UTF-8 are rejected.',faq=('Should I encode a full URL or a parameter?','Use query parameter mode for individual values such as search text. Full URL mode preserves separators such as /, ?, and &.')),
 dict(slug='jwt-decoder',action='jwt-decoder',icon='JWT',title='JWT Decoder',category='Developer',desc='Inspect JWT headers and payloads locally, without sending the token anywhere.',fields=text('JWT','xxxxx.yyyyy.zzzzz'),button='Decode JWT',note='This tool decodes JWT contents. It does NOT verify the signature.',how='Python decodes base64url header/payload segments and parses strict JSON. Standard date claims are shown as UTC, without validating their authenticity.',faq=('Can I trust the decoded claims?','No. All claims are unverified. This tool does not fetch issuer URLs or keys, authenticate tokens, or support encrypted five-segment JWE.')),
 dict(slug='qr-generator',action='qr-generator',icon='▦',title='QR Code Generator',category='Utility',desc='Turn text or a URL into a local QR code, with PNG and SVG downloads.',fields=text('Text or URL','https://example.com')+select('size','Image size',[('512','512 × 512'),('256','256 × 256'),('1024','1024 × 1024')])+select('correction','Error correction',[('MEDIUM','Medium (M)'),('LOW','Low (L)'),('QUARTILE','Quartile (Q)'),('HIGH','High (H)')]),button='Generate QR code',note='QR contents are readable by anyone who scans the image. No external QR service is used.',how='The bundled Nayuki JavaScript library calculates the QR matrix. Modules use integer pixel sizes and a quiet zone of at least four modules.',faq=('Why might a long message fail?','QR capacity is finite, and stronger error correction reduces it. Shorten the text or choose a lower correction level.')),
]


def generate():
    cards = ''
    for i, tool in enumerate(TOOLS):
        slug, category, title, desc = (tool[k] for k in ['slug','category','title','desc'])
        search = escape((title+' '+desc+' '+category+(' developer' if slug=='uuid-generator' else '')).lower(), quote=True)
        cards += f'<a class="tool-card" href="tools/{slug}/" data-category="{category.lower()}" data-search="{search}"><span class="tool-icon icon-{i%6}" aria-hidden="true">{tool["icon"]}</span><div class="card-content"><span class="category">{category}</span><h3>{title}</h3><p>{desc}</p></div><span class="card-arrow" aria-hidden="true">↗</span></a>'
    filters = '<button class="active" data-filter="all" aria-pressed="true">All tools <span>20</span></button>'+''.join(f'<button data-filter="{c.lower()}" aria-pressed="false">{c}</button>' for c in ['Files','Privacy','Data','Text','Developer','Utility'])
    body = f'''<section class="catalog-intro"><div><h1>Tools for everyday tasks.</h1><p>Work with files, images, text, and data — right in your browser.</p></div><span class="catalog-total">20 tools <span aria-hidden="true">/</span> 6 categories</span></section>
<section class="catalog" id="tools" aria-label="Tool catalog">
  <div class="catalog-controls">
    <label class="search"><svg aria-hidden="true" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/></svg><input id="search" type="search" placeholder="Search tools…" aria-label="Find a tool" autocomplete="off"></label>
    <div class="catalog-bar"><div class="filters" role="group" aria-label="Filter tools">{filters}</div><span id="tool-count" class="muted" aria-live="polite">20 tools</span></div>
  </div>
  <div class="tool-grid">{cards}</div>
  <p id="no-tools" hidden>No tools found. Try another search or category.</p>
</section>
<p class="catalog-note">Files and text are processed on your device. <a href="about/">How it works</a></p>'''
    (ROOT/'index.html').write_text(page('Browser tools','Twenty browser utilities for files, images, text, and data.',body,home=True))
    for tool in TOOLS:
        slug, action, category, title, desc = (tool[k] for k in ['slug','action','category','title','desc'])
        image = action.startswith('image-')
        inspect = '<button id="inspect" class="secondary" type="button">Inspect image</button><div id="image-info" aria-live="polite"></div>' if image else ''
        body=f'''<div class="tool-page"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="../../">Home</a><span>/</span><a href="../../?category={category.lower()}#tools">{category}</a><span>/ {title}</span></nav><div class="tool-title"><span class="tool-icon" aria-hidden="true">{tool['icon']}</span><span class="eyebrow">{category.upper()} / LOCAL PROCESSING</span></div><h1>{title}</h1><p class="intro">{desc}</p><div class="workspace"><section class="input-panel"><div class="panel-heading"><h2>01 <span>Input</span></h2><span class="local-label">● Local only</span></div><form id="tool-form"><fieldset id="controls">{tool['fields']}{inspect}<p class="tool-note{' warning' if action=='jwt-decoder' else ''}">{tool['note']}</p><button class="primary" type="submit">{tool['button']} <span aria-hidden="true">→</span></button><button id="clear" class="secondary" type="button">Clear</button></fieldset><button id="cancel" class="secondary" type="button" hidden>Cancel processing</button></form><noscript><p class="error">Enable JavaScript to run these local tools.</p></noscript></section><section class="result-panel" id="result-panel" aria-labelledby="result-heading"><div class="panel-heading"><h2 id="result-heading">02 <span>Result</span></h2><button id="copy" class="secondary compact" type="button" hidden>Copy result</button></div><p id="status" role="status" aria-live="polite">Ready when you are. {'QR runs locally without Python.' if action=='qr-generator' else 'The Python engine loads on first use.'}</p><progress id="progress" max="100" value="0" hidden aria-label="File processing progress"></progress><div id="result-empty" class="result-empty"><span aria-hidden="true">↳</span><h3>A little space for your result.</h3><p>Processed locally in your browser.</p></div><label class="sr-only" for="result-text">Result</label><textarea id="result-text" readonly rows="12" hidden spellcheck="false"></textarea><div id="result-details"></div><img id="preview" alt="Generated result preview" hidden><a id="download" class="primary download" download hidden>Download result ↓</a><a id="download-svg" class="secondary download" download hidden>Download SVG ↓</a></section></div><aside class="privacy-inline"><strong>⌂ &nbsp; Processed locally in your browser</strong><p>Your input is never uploaded. No account, analytics, or saved history. Python tools download runtime files from jsDelivr on demand.</p></aside><section class="tool-explanation"><h2>About this tool</h2><p>{desc}</p><h2>How it works</h2><p>{tool['how']}</p><h2>FAQ</h2><details><summary>{tool['faq'][0]}</summary><p>{tool['faq'][1]}</p></details></section></div>'''
        path = ROOT/'tools'/slug/'index.html'
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(page(title, desc, body, '../../', action))
    # Full compatible pages retain existing links and browser clients.
    for old,new in [('hash','file-hash'),('image-metadata','remove-image-metadata'),('json','json-formatter')]:
        source = (ROOT/'tools'/new/'index.html').read_text()
        (ROOT/'tools'/old/'index.html').write_text(source.replace('<title>', f'<link rel="canonical" href="../{new}/">\n<title>',1))


if __name__ == '__main__':
    generate()
